// GET ALL
export const GET_ALL_FACULTY_REQUEST ='GET_ALL_FACULTY_REQUEST';
export const GET_ALL_FACULTY_RESPONSE ='GET_ALL_FACULTY_RESPONSE';
export const GET_ALL_FACULTY_FAILED ='GET_ALL_FACULTY_FAILED';

// GET
export const GET_FACULTY_REQUEST ='GET_FACULTY_REQUEST';
export const GET_FACULTY_RESPONSE ='GET_FACULTY_RESPONSE';
export const GET_FACULTY_FAILED ='GET_FACULTY_FAILED';

// ADD
export const ADD_FACULTY_REQUEST ='ADD_FACULTY_REQUEST';
export const ADD_FACULTY_RESPONSE ='ADD_FACULTY_RESPONSE';
export const ADD_FACULTY_FAILED ='ADD_FACULTY_FAILED';

// EDIT
export const EDIT_FACULTY_REQUEST ='EDIT_FACULTY_REQUEST';
export const EDIT_FACULTY_RESPONSE ='EDIT_FACULTY_RESPONSE';
export const EDIT_FACULTY_FAILED ='EDIT_FACULTY_FAILED';

// DELETE
export const DELETE_FACULTY_REQUEST ='DELETE_FACULTY_REQUEST';
export const DELETE_FACULTY_RESPONSE ='DELETE_FACULTY_RESPONSE';
export const DELETE_FACULTY_FAILED ='DELETE_FACULTY_FAILED';
