export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_RESPONSE = 'GET_USER_RESPONSE';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_RESPONSE = 'EDIT_USER_RESPONSE';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const EDIT_USER_IMAGE_REQUEST = 'EDIT_USER_IMAGE_REQUEST';
export const EDIT_USER_IMAGE_RESPONSE = 'EDIT_USER_IMAGE_RESPONSE';
export const EDIT_USER_IMAGE_FAILED = 'EDIT_USER_IMAGE_FAILED';

export const EDIT_USER_PASSWORD_REQUEST = 'EDIT_USER_PASSWORD_REQUEST';
export const EDIT_USER_PASSWORD_RESPONSE = 'EDIT_USER_PASSWORD_RESPONSE';
export const EDIT_USER_PASSWORD_FAILED = 'EDIT_USER_PASSWORD_FAILED';

export const CLOSE_USER_SUCCESS_MESSAGE = 'CLOSE_USER_SUCCESS_MESSAGE';
export const CLOSE_USER_ERROR_MESSAGE = 'CLOSE_USER_ERROR_MESSAGE';

export const RESET_USER_STATE = 'RESET_USER_STATE';
