// GET
export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_RESPONSE = 'GET_COURSE_RESPONSE';
export const GET_COURSE_FAILED = 'GET_COURSE_FAILED';

// ADD
export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST';
export const ADD_COURSE_RESPONSE = 'ADD_COURSE_RESPONSE';
export const ADD_COURSE_FAILED = 'ADD_COURSE_FAILED';

// EDIT
export const EDIT_COURSE_REQUEST = 'EDIT_COURSE_REQUEST';
export const EDIT_COURSE_RESPONSE = 'EDIT_COURSE_RESPONSE';
export const EDIT_COURSE_FAILED = 'EDIT_COURSE_FAILED';

// DELETE
export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_RESPONSE = 'DELETE_COURSE_RESPONSE';
export const DELETE_COURSE_FAILED = 'DELETE_COURSE_FAILED';
