// GET
export const GET_TIMING_REQUEST = 'GET_TIMING_REQUEST';
export const GET_TIMING_RESPONSE = 'GET_TIMING_RESPONSE';
export const GET_TIMING_FAILED = 'GET_TIMING_FAILED';

// ADD
export const ADD_TIMING_REQUEST = 'ADD_TIMING_REQUEST';
export const ADD_TIMING_RESPONSE = 'ADD_TIMING_RESPONSE';
export const ADD_TIMING_FAILED = 'ADD_TIMING_FAILED';

// EDIT
export const EDIT_TIMING_REQUEST = 'EDIT_TIMING_REQUEST';
export const EDIT_TIMING_RESPONSE = 'EDIT_TIMING_RESPONSE';
export const EDIT_TIMING_FAILED = 'EDIT_TIMING_FAILED';

// DELETE
export const DELETE_TIMING_REQUEST = 'DELETE_TIMING_REQUEST';
export const DELETE_TIMING_RESPONSE = 'DELETE_TIMING_RESPONSE';
export const DELETE_TIMING_FAILED = 'DELETE_TIMING_FAILED';
