// GET
export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_RESPONSE = 'GET_CATEGORY_RESPONSE';
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED';

// ADD
export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_RESPONSE = 'ADD_CATEGORY_RESPONSE';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

// EDIT
export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST';
export const EDIT_CATEGORY_RESPONSE = 'EDIT_CATEGORY_RESPONSE';
export const EDIT_CATEGORY_FAILED = 'EDIT_CATEGORY_FAILED';

// DELETE
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_RESPONSE = 'DELETE_CATEGORY_RESPONSE';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
