export const ENABLE_ADD_BATCH_LOADER = 'ENABLE_ADD_BATCH_LOADER';
export const DISABLE_ADD_BATCH_LOADER = 'DISABLE_ADD_BATCH_LOADER';

export const ADD_BATCH_REQUEST = 'ADD_BATCH_REQUEST';
export const ADD_BATCH_RESPONSE = 'ADD_BATCH_RESPONSE';
export const ADD_BATCH_FAILED = 'ADD_BATCH_FAILED';

export const GET_ALL_BATCH_REQUEST = 'GET_ALL_BATCH_REQUEST';
export const GET_ALL_BATCH_RESPONSE = 'GET_ALL_BATCH_RESPONSE';
export const GET_ALL_BATCH_FAILED = 'GET_ALL_BATCH_FAILED';

export const GET_BATCH_REQUEST = 'GET_BATCH_REQUEST';
export const GET_BATCH_RESPONSE = 'GET_BATCH_RESPONSE';
export const GET_BATCH_FAILED = 'GET_BATCH_FAILED';
export const EDIT_BATCH_REQUEST = 'EDIT_BATCH_REQUEST';
export const EDIT_BATCH_RESPONSE = 'EDIT_BATCH_RESPONSE';
export const EDIT_BATCH_FAILED = 'EDIT_BATCH_FAILED';

export const DELETE_BATCH_REQUEST = 'DELETE_BATCH_REQUEST';
export const DELETE_BATCH_RESPONSE = 'DELETE_BATCH_RESPONSE';
export const DELETE_BATCH_FAILED = 'DELETE_BATCH_FAILED';

export const GET_COURSES_BATCH_REQUEST = 'GET_COURSES_BATCH_REQUEST';
export const GET_COURSES_BATCH_RESPONSE = 'GET_COURSES_BATCH_RESPONSE';
export const GET_COURSES_BATCH_FAILED = 'GET_COURSES_BATCH_FAILED';

export const CLOSE_BATCH_SUCCESS_MESSAGE = 'CLOSE_BATCH_SUCCESS_MESSAGE';
export const CLOSE_BATCH_ERROR_MESSAGE = 'CLOSE_BATCH_ERROR_MESSAGE';


export const CLEAR_BATCH_LIST="CLEAR_BATCH_LIST"