export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_RESPONSE = 'OTP_RESPONSE';
export const OTP_FAILED = 'OTP_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const GET_LOGIN_USER_TYPES_REQUEST = 'GET_LOGIN_USER_TYPES_REQUEST';
export const GET_LOGIN_USER_TYPES_RESPONSE = 'GET_LOGIN_USER_TYPES_RESPONSE';
export const GET_LOGIN_USER_TYPES_FAILED = 'GET_LOGIN_USER_TYPES_FAILED';

export const CLEAR_LOGIN_USER_TYPES_REQUEST = 'CLEAR_LOGIN_USER_TYPES_REQUEST';
export const CLEAR_LOGIN_USER_TYPES_RESPONSE =
  'CLEAR_LOGIN_USER_TYPES_RESPONSE';
export const CLEAR_LOGIN_USER_TYPES_FAILED = 'CLEAR_LOGIN_USER_TYPES_FAILED';
