export const GET_PRIVILEGES_REQUEST = 'GET_PRIVILEGES_REQUEST';
export const GET_PRIVILEGES_RESPONSE = 'GET_PRIVILEGES_RESPONSE';
export const GET_PRIVILEGES_FAILED = 'GET_PRIVILEGES_FAILED';

export const UPDATE_PRIVILEGES_REQUEST = 'UPDATE_PRIVILEGES_REQUEST';
export const UPDATE_PRIVILEGES_RESPONSE = 'UPDATE_PRIVILEGES_RESPONSE';
export const UPDATE_PRIVILEGES_FAILED = 'UPDATE_PRIVILEGES_FAILED';

export const ENABLE_GET_PRIVILEGES_LOADER = 'ENABLE_GET_PRIVILEGES_LOADER';
export const DISABLE_GET_PRIVILEGES_LOADER = 'DISABLE_GET_PRIVILEGES_LOADER';

export const ENABLE_UPDATE_PRIVILEGES_LOADER =
  'ENABLE_UPDATE_PRIVILEGES_LOADER';
export const DISABLE_UPDATE_PRIVILEGES_LOADER =
  'DISABLE_UPDATE_PRIVILEGES_LOADER';

export const CLOSE_PRIVILEGES_SUCCESS_MESSAGE =
  'CLOSE_PRIVILEGES_SUCCESS_MESSAGE';
export const CLOSE_PRIVILEGES_ERROR_MESSAGE = 'CLOSE_PRIVILEGES_ERROR_MESSAGE';

export const GET_USERS_PRIVILEGES_REQUEST = 'GET_USERS_PRIVILEGES_REQUEST';
export const GET_USERS_PRIVILEGES_RESPONSE = 'GET_USERS_PRIVILEGES_RESPONSE';
export const GET_USERS_PRIVILEGES_FAILED = 'GET_USERS_PRIVILEGES_FAILED';

export const GET_ADMIN_PRIVILEGES_REQUEST = 'GET_ADMIN_PRIVILEGES_REQUEST';
export const GET_ADMIN_PRIVILEGES_RESPONSE = 'GET_ADMIN_PRIVILEGES_RESPONSE';
export const GET_ADMIN_PRIVILEGES_FAILED = 'GET_ADMIN_PRIVILEGES_FAILED';
export const GET_SUPER_ADMIN_PRIVILEGES_REQUEST =
  'GET_SUPER_ADMIN_PRIVILEGES_REQUEST';
export const GET_SUPER_ADMIN_PRIVILEGES_RESPONSE =
  'GET_SUPER_ADMIN_PRIVILEGES_RESPONSE';
export const GET_SUPER_ADMIN_PRIVILEGES_FAILED =
  'GET_SUPER_ADMIN_PRIVILEGES_FAILED';
