// GET ALL
export const GET_ALL_STUDENT_REQUEST ='GET_ALL_STUDENT_REQUEST';
export const GET_ALL_STUDENT_RESPONSE ='GET_ALL_STUDENT_RESPONSE';
export const GET_ALL_STUDENT_FAILED ='GET_ALL_STUDENT_FAILED';

// GET
export const GET_STUDENT_REQUEST ='GET_STUDENT_REQUEST';
export const GET_STUDENT_RESPONSE ='GET_STUDENT_RESPONSE';
export const GET_STUDENT_FAILED ='GET_STUDENT_FAILED';

// ADD
export const ADD_STUDENT_REQUEST ='ADD_STUDENT_REQUEST';
export const ADD_STUDENT_RESPONSE ='ADD_STUDENT_RESPONSE';
export const ADD_STUDENT_FAILED ='ADD_STUDENT_FAILED';

// EDIT
export const EDIT_STUDENT_REQUEST ='EDIT_STUDENT_REQUEST';
export const EDIT_STUDENT_RESPONSE ='EDIT_STUDENT_RESPONSE';
export const EDIT_STUDENT_FAILED ='EDIT_STUDENT_FAILED';

// DELETE
export const DELETE_STUDENT_REQUEST ='DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_RESPONSE ='DELETE_STUDENT_RESPONSE';
export const DELETE_STUDENT_FAILED ='DELETE_STUDENT_FAILED';
