// GET
export const GET_SUBJECTS_REQUEST = 'GET_SUBJECTS_REQUEST';
export const GET_SUBJECTS_RESPONSE = 'GET_SUBJECTS_RESPONSE';
export const GET_SUBJECTS_FAILED = 'GET_SUBJECTS_FAILED';

// ADD
export const ADD_SUBJECTS_REQUEST = 'ADD_SUBJECTS_REQUEST';
export const ADD_SUBJECTS_RESPONSE = 'ADD_SUBJECTS_RESPONSE';
export const ADD_SUBJECTS_FAILED = 'ADD_SUBJECTS_FAILED';

// EDIT
export const EDIT_SUBJECTS_REQUEST = 'EDIT_SUBJECTS_REQUEST';
export const EDIT_SUBJECTS_RESPONSE = 'EDIT_SUBJECTS_RESPONSE';
export const EDIT_SUBJECTS_FAILED = 'EDIT_SUBJECTS_FAILED';

// DELETE
export const DELETE_SUBJECTS_REQUEST = 'DELETE_SUBJECTS_REQUEST';
export const DELETE_SUBJECTS_RESPONSE = 'DELETE_SUBJECTS_RESPONSE';
export const DELETE_SUBJECTS_FAILED = 'DELETE_SUBJECTS_FAILED';
